require("plugins")
-- require("autocommands")
-- require("autopairs")
-- require("bufferline")
-- require("cmp")
-- require("colorscheme")
-- require("comment")
-- require("dap")
-- require("doge")
-- require("gitsigns")
-- require("illuminate")
-- require("impatient")
-- require("indentline")
require("keymaps")
-- require("lualine")
require("options")
-- require("project")
-- require("telescope")
-- require("toggleterm")
-- require("tokyonight")
-- require("treesitter")
-- require("trouble")
